use containerdb;

CREATE TABLE IF NOT EXISTS tbl_plain (

    ID INT(11) AUTO_INCREMENT,
    WEIGHT VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,   
    PRICE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;

INSERT INTO tbl_plain (WEIGHT, IMAGE, PRICE) VALUES ('250g', 'plain', '$15.90');
INSERT INTO tbl_plain (WEIGHT, IMAGE, PRICE) VALUES ('500g', 'plain', '$24.90');
INSERT INTO tbl_plain (WEIGHT, IMAGE, PRICE) VALUES ('1kg', 'plain', '$33.90');