use containerdb;

CREATE TABLE IF NOT EXISTS tbl_umf18 (

    ID INT(11) AUTO_INCREMENT,
    WEIGHT VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,   
    PRICE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;

INSERT INTO tbl_umf18 (WEIGHT, IMAGE, PRICE) VALUES ('250g', 'umf_18', '$55.90');
INSERT INTO tbl_umf18 (WEIGHT, IMAGE, PRICE) VALUES ('500g', 'umf_18', '$89.90');
INSERT INTO tbl_umf18 (WEIGHT, IMAGE, PRICE) VALUES ('1kg', 'umf_18', '$119.90');