use containerdb;

CREATE TABLE IF NOT EXISTS tbl_umf15 (

    ID INT(11) AUTO_INCREMENT,
    WEIGHT VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,   
    PRICE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;

INSERT INTO tbl_umf15 (WEIGHT, IMAGE, PRICE) VALUES ('250g', 'streamland_15', '$39.90');
INSERT INTO tbl_umf15 (WEIGHT, IMAGE, PRICE) VALUES ('500g', 'UMF_15_500g', '$49.90');
INSERT INTO tbl_umf15 (WEIGHT, IMAGE, PRICE) VALUES ('1kg', 'streamland_15', '$59.90');