use containerdb;

CREATE TABLE IF NOT EXISTS tbl_umf10 (

    ID INT(11) AUTO_INCREMENT,
    WEIGHT VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,   
    PRICE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;

INSERT INTO tbl_umf10 (WEIGHT, IMAGE, PRICE) VALUES ('250g', 'comvita_10', '$29.90');
INSERT INTO tbl_umf10 (WEIGHT, IMAGE, PRICE) VALUES ('500g', 'comvita_10_500g', '$39.90');
INSERT INTO tbl_umf10 (WEIGHT, IMAGE, PRICE) VALUES ('1kg', 'comvita_10', '$49.90');