use containerdb;

CREATE TABLE IF NOT EXISTS tbl_umf8 (
    ID INT(11) AUTO_INCREMENT,
    WEIGHT VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,   
    PRICE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
) AUTO_INCREMENT = 1;

INSERT INTO tbl_umf8 (WEIGHT, IMAGE, PRICE) VALUES ('250g', 'WILDERNESS_8', '$25.90');
INSERT INTO tbl_umf8 (WEIGHT, IMAGE, PRICE) VALUES ('500g', 'WILDERNESS_8', '$36.90');
INSERT INTO tbl_umf8 (WEIGHT, IMAGE, PRICE) VALUES ('1kg', 'streamland_5', '$42.90');